import jQuery from "./core.js";

import "./selector";
import "./traversing";
import "./callbacks";
import "./deferred";
import "./deferred/exceptionHook";
import "./core/ready";
import "./data";
import "./queue";
import "./queue/delay";
import "./attributes";
import "./event";
import "./event/trigger";
import "./manipulation";
import "./manipulation/_evalUrl";
import "./wrap";
import "./css";
import "./css/hiddenVisibleSelectors";
import "./css/showHide";
import "./serialize";
import "./ajax";
import "./ajax/xhr";
import "./ajax/script";
import "./ajax/jsonp";
import "./ajax/load";
import "./core/parseXML";
import "./core/parseHTML";
import "./effects";
import "./effects/animatedSelector";
import "./offset";
import "./dimensions";
import "./deprecated";
import "./exports/amd";
import "./exports/global";

export default jQuery;
